# Generated by Django 2.1.3 on 2018-11-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejercito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mazos.Arena')),
            ],
        ),
        migrations.CreateModel(
            name='Tropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ejercito',
            name='tropa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mazos.Tropa'),
        ),
        migrations.AddField(
            model_name='arena',
            name='tropas',
            field=models.ManyToManyField(through='mazos.Ejercito', to='mazos.Tropa'),
        ),
    ]
